version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - rabbitmq_go_net

  postgres:
    image: postgres:14.1
    container_name: 'postgres'
    restart: always
    environment:
        - POSTGRES_DB=RABBIT_CALCULATOR
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
        - '6543:5432'

networks:
  rabbitmq_go_net:
    driver: bridge