// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RabbitMQCalculator.UseCases.Shared.Database.Context;

#nullable disable

namespace RabbitMQCalculator.UseCases.Shared.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220108142123_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RabbitMQCalculator.UseCases.Domain.Calculation.CalculationEntity", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Error")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("FirstNumber")
                        .HasColumnType("double precision");

                    b.Property<char>("Operator")
                        .HasColumnType("character(1)");

                    b.Property<double>("Result")
                        .HasColumnType("double precision");

                    b.Property<double>("SecondNumber")
                        .HasColumnType("double precision");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Guid");

                    b.ToTable("Calculations");
                });
#pragma warning restore 612, 618
        }
    }
}
